### ISSUE TITLE
An error occurred while running `run_r2r_xl.sh`.

### ISSUE THREAD

**Issue by yds3** [GengzeZhou/NavGPT-2#6]
Hello, your paper is excellent, but when I ran the script, the code encountered an error as shown in the attached image. Could you please advise on how to resolve this issue?
![微信图片_20241015123201](https://github.com/user-attachments/assets/d7cbe08b-13b0-412f-b0a5-43655d16b878)

**Comment by GengzeZhou** [comment]
Thanks for pointing out the question. Did you encounter this problem after the first iteration or a few iterations?

**Comment by yds3** [comment]
Thank you for your reply. I followed the instructions in the readme file and skipped Stage 1: Visual Instruction Tuning of NavGPT-2, proceeding directly to Stage 2: Policy Finetuning of NavGPT-2. However, when I ran run_r2r_xl.sh, I encountered the error right at the start, which I believe occurred during the first iteration.

Additionally, could I trouble you to let me know the memory size of a single A100 GPU? When I tried to run run_r2r_xxl.sh on a 16GB GPU, I received an out-of-memory error.

**Comment by GengzeZhou** [comment]
I will debug and fix the problem later. The problem could happen because I refined the codebase when releasing.

Here is some hint to solve the issue, the problem could happen when loading model weight with float16 and training with float32, the weights would overflow after the first update. Check the weights of the model after loading it or directly transferring them to full precision might help. Otherwise, check the input data and make sure the input features are not Nan.

For training the xxl model we used an 80GB A100 GPU, but this could be done on a single 40GB A100 by setting the accumulate_gradient_steps or simply removing the very long trajectories in the training set.

**Comment by yds3** [comment]
Thank you very much for your reply.

**Comment by GengzeZhou** [comment]
I tested the code on my end and didn't encounter the same issue. Were you able to resolve the problem? If you need further assistance, I'd be happy to help.

**Comment by explore-2001** [comment]
您好，我想请问您在A100,80G的显卡上运行run_r2r_xl.sh时，训练了多少时间，是否有可以缩短训练时间的方法？
